version: '3.8'

services:
  ## database
  mariadb:
    image: mariadb:latest
    container_name: fontory-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootPW
      MYSQL_DATRABASE: FONTORY
      MYSQL_USER: fontory
      MYSQL_PASSWORD: fontoryPW
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/vat/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: fontory-redis
    ports:
      - "6379:6379"
    networks:
      - backend

 ## monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: fontory-prometheus
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus-config.yaml'
    ports:
      - "9090:9090"
    networks:
      - monitoring-network

  loki:
    image: grafana/loki:latest
    container_name: fontory-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    container_name: fontory-grafana
#    set in instance
#    environment:
#      - GF_SECURITY_ADMIN_USER=local
#      - GF_SECURITY_ADMIN_PASSWORD=local
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - monitoring-network

networks:
  backend:
    driver: bridge
  monitoring-network:
    driver: bridge

volumes:
  mysql_data:
  loki_data: